{
 "title": "Mission Control Panels",
 "tags": [ "demo" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AdtEndpoint", "query": "'[ISS_ADT_ENDPOINT]'" },
   {
    "name": "SelectedPanel",
    "query": "// Get all disciplines\nlet ADTendpoint = $AdtEndpoint;\nlet ADTquery = \n```SELECT t.$dtId as tid FROM DIGITALTWINS t\n   WHERE IS_OF_MODEL(t , 'dtmi:com:iss:discipline;1') AND $dtId != 'MISSIONCONTROL'```;\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery) \n| extend tid_string = tostring(tid)\n| project-away tid"
   },
   {
    "name": "Sensor",
    "query": "// Get all factories\nlet ADTendpoint = $AdtEndpoint;\nlet ADTquery= ```SELECT sensor.Description as tid FROM digitaltwins MATCH (component)-[:HasMember]->(sensor)\nWHERE component.$dtId = '$SelectedPanel' AND IS_OF_MODEL(sensor,'dtmi:com:microsoft:autoingest:IssSensor;1', exact) ```;\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| project tid_string = tostring(tid)\n| sort by tid_string asc"
   },
   { "name": "DataHistoryTable", "query": "[ISS_DATABASE_TABLE_NAME]" }
  ]
 },
 "panels": [
  {
   "title": "$Sensor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = $AdtEndpoint;\nlet ADTSensorId = \"SELECT t.$dtId as tid FROM digitaltwins t where t.Description = '$Sensor'\";\nlet sensorTwinId = toscalar(evaluate azure_digital_twins_query_request(ADTendpoint, ADTSensorId)\n| project sensor_tid = tostring(tid));\n$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp) or $__timeFilter(TimeStamp) \n| where Id == sensorTwinId and (Key == \"Value\")\n| project TimeStamp=iif($__timeFilter(SourceTimeStamp), SourceTimeStamp, TimeStamp), Value=todouble(Value), Id\n| order by TimeStamp asc \n\n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "$Sensor ",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = $AdtEndpoint;\nlet ADTSensorId = \"SELECT t.$dtId as tid FROM digitaltwins t where t.Description = '$Sensor'\";\nlet sensorTwinId = toscalar(evaluate azure_digital_twins_query_request(ADTendpoint, ADTSensorId)\n| project sensor_tid = tostring(tid));\n$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp) or $__timeFilter(TimeStamp) \n| where Id == sensorTwinId and (Key == \"Value\")\n| project TimeStamp=iif($__timeFilter(SourceTimeStamp), SourceTimeStamp, TimeStamp), Value=todouble(Value)\n| order by TimeStamp desc \n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "$Sensor State",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = $AdtEndpoint;\nlet ADTSensorId = \"SELECT t.$dtId as tid, t.ENUM as enum FROM digitaltwins t where t.Description = '$Sensor' AND is_defined(t.ENUM) AND not is_null(t.ENUM)\";\nlet sensorDetails = evaluate azure_digital_twins_query_request(ADTendpoint, ADTSensorId) \n                    | project sensor_tid = tostring(tid), sensor_enum = split(tostring(enum), '; ');\n$DataHistoryTable\n| where ($__timeFilter(SourceTimeStamp) or $__timeFilter(TimeStamp)) and Key == 'Value'\n| join kind=inner sensorDetails on $left.Id == $right.sensor_tid\n| where Id == sensor_tid\n| mv-apply sensor_enum on (where sensor_enum startswith strcat(tostring(Value), '=') | project state = split(sensor_enum, '=' ,1 ))\n| project  SourceTimeStamp=iif($__timeFilter(SourceTimeStamp), SourceTimeStamp, TimeStamp), Value=tostring(state[0])\n| order by SourceTimeStamp asc \n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Digital Twin ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = $AdtEndpoint;\nlet ADTSensorId = \"SELECT t.$dtId as tid FROM digitaltwins t where t.Description = '$Sensor'\";\nlet sensorTwinId = toscalar(evaluate azure_digital_twins_query_request(ADTendpoint, ADTSensorId)\n| project sensor_tid = tostring(tid));\n$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp) or $__timeFilter(TimeStamp) \n| where Id == sensorTwinId and (Key == \"Value\")\n| project TimeStamp=iif($__timeFilter(SourceTimeStamp), SourceTimeStamp, TimeStamp), Id\n| order by TimeStamp  asc \n\n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = $AdtEndpoint;\nlet ADTSensorId = \"SELECT t.$dtId as tid FROM digitaltwins t where t.Description = '$Sensor'\";\nlet sensorTwinId = toscalar(evaluate azure_digital_twins_query_request(ADTendpoint, ADTSensorId));\nlet sensor_description = toscalar(adt_dh_ah_iss_adt_02_westeurope | where Id == sensorTwinId and Key == 'Description' | summarize take_any(Value));\nlet sub_descriptions = split(toscalar(sensor_description), \" \");\niss_events\n| where datetime_diff(\"day\",  $__timeFrom, Date) <=2\n| where Description has_any(sub_descriptions)\n| project Date, Event, Description\n| order by Date asc ",
     "querySource": "raw"
    }
   ]
  }
 ]
}