{
 "title": "ISS Position",
 "tags": [ "demo" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DataHistoryTable", "query": "[ISS_DATABASE_TABLE_NAME]" }
  ]
 },
 "panels": [
  {
   "title": "ISS Video Feed",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"100%\" src=\"https://www.ustream.tv/embed/17074538\" scrolling=\"no\" allowfullscreen webkitallowfullscreen frameborder=\"0\" style=\"border: 0 none transparent;\"></iframe>"
   }
  },
  {
   "title": "ISS Position",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "[ISS_DATABASE-NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp) and (Id == 'GroundPosition')\n| where Key == 'Latitude' or Key == 'Longitude' or Key == 'Altitude'\n| project SourceTimeStamp, Key, Value=todouble(Value)\n| evaluate pivot(Key, any(Value), SourceTimeStamp)\n| project SourceTimeStamp, Latitude , Longitude, Altitude=Altitude * 1000, pctTime =  100 * (todouble(datetime_diff('Minute', now(), SourceTimeStamp)) /  todouble(datetime_diff('Minute', now(), $__timeFrom))) ",
     "querySource": "raw"
    },
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "datatable(Latitude:double, Longitude:double, Id:string)[\n     29.558056,  -95.088333, 'MCC-H',\n     55.916667, 37.816667, 'MCC-M',\n     36.083472, 140.076444, 'Tsukuba',\n     48.078056, 11.2525, 'Mission Control Munich',\n     45.4825, -73.419722, 'Montreal',\n     38.951667, -77.448056, 'MCC-D',\n     33.917222, -118.348611, 'MCC-X',\n     34.73, -86.585, 'Huntsville'\n]\n| project Name = Id, GsLatitude=Latitude, GsLongitude=Longitude,Altitude=0",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Orbital Velocity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let eDate = $__timeTo;\nlet sDate = $__timeFrom;\nlet resolution = 1000;\nlet makeseriessteps = (eDate-sDate)/resolution;\n$DataHistoryTable\n| where SourceTimeStamp between (sDate..eDate)\n| where Key == 'Value' and (Id == 'USLAB000035' or Id == 'USLAB000036' or Id == 'USLAB000037')\n| project Value=todouble(Value), SourceTimeStamp, Id=tostring(Id)\n| summarize Value=avg(Value) by Id, bin(SourceTimeStamp, 1s)\n| evaluate pivot(Id, any(Value))\n| extend OrbitalVelocitymps = sqrt(pow(USLAB000035,2)+pow(USLAB000036,2)+pow(USLAB000037,2))\n| project SourceTimeStamp, OrbitalVelocitykmph = todouble(OrbitalVelocitymps * 3600/1000)\n| make-series OrbitalVelocitykmph=avg(OrbitalVelocitykmph) default = double(null) on SourceTimeStamp step $__timeInterval\n| extend OrbitalVelocitykmph=series_fill_linear(OrbitalVelocitykmph, double(null), true)\n| mv-expand SourceTimeStamp to typeof(datetime), OrbitalVelocitykmph to typeof(double)\n| order by SourceTimeStamp asc\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Orbital Velocity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "$DataHistoryTable\n| where $__timeFilter(TimeStamp)\n| where Key == 'Value' and (Id == 'USLAB000035' or Id == 'USLAB000036' or Id == 'USLAB000037')\n| summarize Value=avg(todouble(Value)) by bin(TimeStamp, 120s), Id \n| evaluate pivot(Id, avg(Value))\n| extend OrbitalVelocitymps = sqrt(pow(USLAB000035,2)+pow(USLAB000036,2)+pow(USLAB000037,2)) \n| project TimeStamp, OrbitalVelocitykmph = OrbitalVelocitymps * 3600/1000\n//| project TimeStamp, OrbitalVelocityMph = (((OrbitalVelocityKmps / 1000) * 3600 )+1000.8 ) / 1.609344\n| order by TimeStamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Altitude (km)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp)\n| where Key == 'Altitude'\n| project SourceTimeStamp, Id, Value=todouble(Value)\n| order by SourceTimeStamp asc\n| render timechart \n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "[ISS_DATABASE_NAME]",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "$DataHistoryTable\n| where $__timeFilter(SourceTimeStamp) and Id == 'GroundPosition' and Key == 'Altitude' \n| project SourceTimeStamp, Id, Value=todouble(Value)\n| order by SourceTimeStamp asc\n| render timechart \n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "ISS Feed",
   "type": "text",
   "gridPos": { "h": 1, "w": 2, "x": 0, "y": 30 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"100%\" src=\"https://ustream.tv/embed/9408562\" scrolling=\"no\" allowfullscreen webkitallowfullscreen frameborder=\"0\" style=\"border: 0 none transparent;\"></iframe>"
   },
   "targets": [
    {
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "adt_dh_ah_iss_adt_02_westeurope\n| where $__timeFilter(TimeStamp)\n| order by TimeStamp asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}