{
 "title": "Machine View by Factory, Machine Type",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Factory",
    "query": "// Get all factories\nlet ADTendpoint = '$AdtEndpoint';\nlet ADTquery = \n```SELECT t.$dtId as tid FROM DIGITALTWINS t\n   WHERE IS_OF_MODEL(t , 'dtmi:assetGen:Factory;1')```;\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)  \n| project tid_string = tostring(tid)\n"
   },
   {
    "name": "MachineType",
    "query": "SaltMachine, PasteurizationMachine"
   },
   {
    "name": "Field1",
    "query": "// Get all factories\nlet ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT TOP(1) t.$dtId as tid FROM DIGITALTWINS t\n   WHERE  STARTSWITH(t.$dtId, '```, \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)  \n| join kind=rightsemi ($DataHistoryTable\n                       | where TimeStamp > ago(1h)) \n   on $left.tid_string == $right.Id\n| distinct Key"
   },
   {
    "name": "Field2",
    "query": "// Get all factories\nlet ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT TOP(1) t.$dtId as tid FROM DIGITALTWINS t\n   WHERE  STARTSWITH(t.$dtId, '```, \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)  \n| join kind=rightsemi ($DataHistoryTable\n                       | where TimeStamp > ago(1h)) \n   on $left.tid_string == $right.Id\n| distinct Key"
   },
   { "name": "DataHistoryTable", "query": "${VAR_DATAHISTORYTABLE}" },
   { "name": "AdtEndpoint", "query": "${VAR_ADTENDPOINT}" }
  ]
 },
 "panels": [
  {
   "title": "$Factory: Comparison of $MachineType $Field1",
   "type": "timeseries",
   "description": "a",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "${VAR_DATAHISTORYDB}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT machine.$dtId as tid FROM DIGITALTWINS\n   MATCH (factory)-[:contains]->(machine)\n   WHERE factory.$dtId = '```, \"$Factory\", \"' and STARTSWITH(machine.$dtId, '\", \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)\n| join kind=rightsemi ($DataHistoryTable \n                       | where $__timeFilter(TimeStamp)\n                         and Key == \"$Field1\") \n    on $left.tid_string == $right.Id\n| extend Value_double = todouble(Value)\n| summarize avg(Value_double) by bin(TimeStamp, 1m), Id\n| sort by TimeStamp asc\n| project-rename $Field1=avg_Value_double\n  \n\n\n\n\n\n\n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "$Factory: Comparison of $MachineType $Field2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "database": "${VAR_DATAHISTORYDB}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT machine.$dtId as tid FROM DIGITALTWINS\n   MATCH (factory)-[:contains]->(machine)\n   WHERE factory.$dtId = '```, \"$Factory\", \"' and STARTSWITH(machine.$dtId, '\", \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)\n| join kind=rightsemi ($DataHistoryTable\n                       | where $__timeFilter(TimeStamp)\n                         and Key == \"$Field2\") \n    on $left.tid_string == $right.Id\n| extend Value_double = todouble(Value)\n| summarize avg(Value_double) by bin(TimeStamp, 1m), Id\n| sort by TimeStamp asc\n| project-rename $Field2=avg_Value_double\n  \n\n\n\n\n\n\n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "$Factory: Total $MachineType $Field1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "${VAR_DATAHISTORYDB}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT machine.$dtId as tid FROM DIGITALTWINS\n   MATCH (factory)-[:contains]->(machine)\n   WHERE factory.$dtId = '```, \"$Factory\", \"' and STARTSWITH(machine.$dtId, '\", \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)\n| join kind=rightsemi ($DataHistoryTable \n                       | where $__timeFilter(TimeStamp)\n                         and Key == \"$Field1\") \n    on $left.tid_string == $right.Id\n| extend Value_double = todouble(Value)\n| summarize avg(Value_double) by bin(TimeStamp, 1m), Id\n| summarize sum(avg_Value_double) by TimeStamp\n| project-rename $Field1 = sum_avg_Value_double\n| sort by TimeStamp asc\n\n\n\n\n  \n\n\n\n\n\n\n\n\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "$Factory: Total $MachineType $Field2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "database": "${VAR_DATAHISTORYDB}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let ADTendpoint = '$AdtEndpoint';\nlet ADTquery = strcat(\n```SELECT machine.$dtId as tid FROM DIGITALTWINS\n   MATCH (factory)-[:contains]->(machine)\n   WHERE factory.$dtId = '```, \"$Factory\", \"' and STARTSWITH(machine.$dtId, '\", \"$MachineType\", \"')\");\nevaluate azure_digital_twins_query_request(ADTendpoint, ADTquery)\n| extend tid_string = tostring(tid)\n| join kind=rightsemi ($DataHistoryTable\n                       | where $__timeFilter(TimeStamp)\n                         and Key == \"$Field2\") \n    on $left.tid_string == $right.Id\n| extend Value_double = todouble(Value)\n| summarize avg(Value_double) by bin(TimeStamp, 1m), Id\n| summarize sum(avg_Value_double) by TimeStamp\n| project-rename $Field2 = sum_avg_Value_double\n| sort by TimeStamp asc\n\n\n\n\n  \n\n\n\n\n\n\n\n\n",
     "querySource": "raw"
    }
   ]
  }
 ]
}