name: CI
on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  # workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab​

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repository content​

      - name: AZ Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Changed Files
        id: changed_files
        uses: tj-actions/changed-files@v32.1.2
        with:
          separator: " "

      - name: Setup Python Environment
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.11.0-rc.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./.pipeline/UploadModels/requirements.txt

      - name: Run Script to Upload Models
        run: |
          python ./.pipeline/UploadModels/main.py ${{ secrets.AZURE_URL }} ${{ steps.changed_files.outputs.all_changed_files }}
